---
    - name: Running Bash Scripts through Ansible
      hosts: all
      gather_facts: no
      tasks:
        - name: return version of nginx
          command: yum info nginx
          register: userScript_output

        - name: Print return information from the previous task
          ansible.builtin.debug:
            var: userScript_output